# path: .github/workflows/ci-pipeline.yml

name: Automated Maven Build, Dockerize, and Deployment

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Java build
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Update Hello World message
        run: |
          sed -i 's/Hello World, this is [^"]*/Hello World, this is Dvorkin Guy on behalf of "Not Just DevOps Species" from Kepler-186f!/' src/main/java/com/myapp/app/App.java

      - name: Set JAR version to 1.0.0
        run: |
          mvn versions:set -DnewVersion=1.0.0

      - name: Increment patch version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          patch_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          mvn versions:set -DnewVersion=$patch_version
          echo "New version: $patch_version"

      - name: Compile the code
        run: mvn compile

      - name: Package the code
        run: mvn package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvorkin-guy-app-jar
          path: target/*.jar

      - name: Build Docker image
        run: |
          docker build -t dvorkinguy/Dvorkin-Guy-From-Kepler-186f-App:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dvorkinguy/Dvorkin-Guy-From-Kepler-186f-App:${{ github.sha }}

      - name: Run the Docker container
        run: docker run -d -p 8080:8080 --name dvorkin-guy-app --user nobody dvorkinguy/Dvorkin-Guy-From-Kepler-186f-App:${{ github.sha }}
